# -*- coding: utf-8 -*-
"""Project Random Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzQ5ZY9aR9avU6GsxKMugF5ZUKqt69UD
"""

#connecting database

import pandas as pd

df = pd.read_csv('/content/sample_data/earthquake_data_tsunami.csv')
#df.info()

#data split

from sklearn.model_selection import train_test_split

X = df.drop('tsunami', axis=1)
y = df['tsunami']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#random forest

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=700, max_features=6, random_state=42)
rf_model.fit(X_train, y_train)

#report old

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = rf_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

#kfold

from sklearn.model_selection import StratifiedKFold, cross_val_score
import numpy as np
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf_model, X, y, cv=skf, scoring='accuracy', n_jobs=-1)

print(f"Cross-validation accuracy scores: {cv_scores}")
print(f"Mean CV accuracy: {np.mean(cv_scores):.4f}")
print(f"Standard deviation of CV accuracy: {np.std(cv_scores):.4f}")

#search for best params

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_dist = {
    'n_estimators': randint(100, 2000), # number of trees
    'max_features': randint(1, X.shape[1]), # number of features to consider for best split
    'max_depth': randint(5, 50), # maximum depth of each tree
    'min_samples_split': randint(2, 20), # minimum samples required to split a node
    'min_samples_leaf': randint(1, 10) # minimum samples required at a leaf node
}

random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_distributions=param_dist,
    n_iter=50,
    cv=skf,
    scoring='accuracy',
    random_state=42,
    n_jobs=-1,
    verbose=1
)

random_search.fit(X, y)

print(f"Best parameters found: {random_search.best_params_}")
print(f"Best cross-validation accuracy: {random_search.best_score_:.4f}")

best_rf_model = random_search.best_estimator_

from sklearn.ensemble import RandomForestClassifier

best_params = {'max_depth': 30, 'max_features': 7, 'min_samples_leaf': 7, 'min_samples_split': 10, 'n_estimators': 306}

final_rf_model = RandomForestClassifier(random_state=42, **best_params)
final_rf_model.fit(X_train, y_train)

# K-fold cross-validation for the tuned model
from sklearn.model_selection import StratifiedKFold, cross_val_score
import numpy as np

final_rf_model = random_search.best_estimator_

cv_scores_tuned = cross_val_score(final_rf_model, X, y, cv=skf, scoring='accuracy', n_jobs=-1)

print(f"Cross-validation accuracy scores for tuned model: {cv_scores_tuned}")
print(f"Mean CV accuracy for tuned model: {np.mean(cv_scores_tuned):.4f}")
print(f"Standard deviation of CV accuracy for tuned model: {np.std(cv_scores_tuned):.4f}")

#report tuned

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred_tuned = best_rf_model.predict(X_test)

accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
print(f"Accuracy of tuned model: {accuracy_tuned:.4f}")
print("\nClassification Report of tuned model:")
print(classification_report(y_test, y_pred_tuned))
print("\nConfusion Matrix of tuned model:")
print(confusion_matrix(y_test, y_pred_tuned))